version: "3.4"
services:
  db:
    image: postgres:14-bullseye
    container_name: <application_name>_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    name: <application_name>_db
