# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HeresAFilm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeresAFilm
  pod 'Cosmos', '~> 23.0'
  pod 'Kingfisher'

  target 'HeresAFilmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeresAFilmUITests' do
    # Pods for testing
  end

end
