name: Verify Migrations

on:
  push:
    branches: [ develop, main ]
    
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: execute flyway in docker compose 🐳
        run: docker-compose up --abort-on-container-exit
